<?php

namespace ContainerCtnGddH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B6dgGiYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b6dgGiY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b6dgGiY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\EvenementController::delete' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController::edit' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController::new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\EvenementController::show' => ['privates', '.service_locator.yAvMNdP', 'get_ServiceLocator_YAvMNdPService', true],
            'App\\Controller\\GategorieEvenementController::delete' => ['privates', '.service_locator.HaFL52N', 'get_ServiceLocator_HaFL52NService', true],
            'App\\Controller\\GategorieEvenementController::edit' => ['privates', '.service_locator.HaFL52N', 'get_ServiceLocator_HaFL52NService', true],
            'App\\Controller\\GategorieEvenementController::index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GategorieEvenementController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GategorieEvenementController::show' => ['privates', '.service_locator.s8Jea._', 'get_ServiceLocator_S8Jea_Service', true],
            'App\\Controller\\TemplateController::indexfront' => ['privates', '.service_locator.oY5GCSX', 'get_ServiceLocator_OY5GCSXService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\EvenementController:delete' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController:edit' => ['privates', '.service_locator.wXSRjZL', 'get_ServiceLocator_WXSRjZLService', true],
            'App\\Controller\\EvenementController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\EvenementController:new' => ['privates', '.service_locator.dRYsSss', 'get_ServiceLocator_DRYsSssService', true],
            'App\\Controller\\EvenementController:show' => ['privates', '.service_locator.yAvMNdP', 'get_ServiceLocator_YAvMNdPService', true],
            'App\\Controller\\GategorieEvenementController:delete' => ['privates', '.service_locator.HaFL52N', 'get_ServiceLocator_HaFL52NService', true],
            'App\\Controller\\GategorieEvenementController:edit' => ['privates', '.service_locator.HaFL52N', 'get_ServiceLocator_HaFL52NService', true],
            'App\\Controller\\GategorieEvenementController:index' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GategorieEvenementController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\GategorieEvenementController:show' => ['privates', '.service_locator.s8Jea._', 'get_ServiceLocator_S8Jea_Service', true],
            'App\\Controller\\TemplateController:indexfront' => ['privates', '.service_locator.oY5GCSX', 'get_ServiceLocator_OY5GCSXService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\EvenementController::delete' => '?',
            'App\\Controller\\EvenementController::edit' => '?',
            'App\\Controller\\EvenementController::index' => '?',
            'App\\Controller\\EvenementController::new' => '?',
            'App\\Controller\\EvenementController::show' => '?',
            'App\\Controller\\GategorieEvenementController::delete' => '?',
            'App\\Controller\\GategorieEvenementController::edit' => '?',
            'App\\Controller\\GategorieEvenementController::index' => '?',
            'App\\Controller\\GategorieEvenementController::new' => '?',
            'App\\Controller\\GategorieEvenementController::show' => '?',
            'App\\Controller\\TemplateController::indexfront' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\EvenementController:delete' => '?',
            'App\\Controller\\EvenementController:edit' => '?',
            'App\\Controller\\EvenementController:index' => '?',
            'App\\Controller\\EvenementController:new' => '?',
            'App\\Controller\\EvenementController:show' => '?',
            'App\\Controller\\GategorieEvenementController:delete' => '?',
            'App\\Controller\\GategorieEvenementController:edit' => '?',
            'App\\Controller\\GategorieEvenementController:index' => '?',
            'App\\Controller\\GategorieEvenementController:new' => '?',
            'App\\Controller\\GategorieEvenementController:show' => '?',
            'App\\Controller\\TemplateController:indexfront' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
