<?php

namespace ContainerItsw2d8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_AyZJp5PService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.AyZJp5P' shared service.
     *
     * @return \Knp\Snappy\Pdf
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\GategorieEvenementController::listCandidats()": the $snappy argument is type-hinted with the non-existent class or interface: "Knp\\Snappy\\Pdf".');
    }
}
