<?php

namespace ContainerItsw2d8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SjEMVkpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SjEMVkp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SjEMVkp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'snappy' => ['privates', '.errored.AyZJp5P', NULL, 'Cannot determine controller argument for "App\\Controller\\GategorieEvenementController::listCandidats()": the $snappy argument is type-hinted with the non-existent class or interface: "Knp\\Snappy\\Pdf".'],
        ], [
            'snappy' => '?',
        ]);
    }
}
