<?php

namespace ContainerItsw2d8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LGlh5OtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lGlh5Ot' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lGlh5Ot'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'evrpo' => ['privates', 'App\\Repository\\EvenementRepo', 'getEvenementRepoService', true],
        ], [
            'evrpo' => 'App\\Repository\\EvenementRepo',
        ]);
    }
}
