<?php

namespace ContainerItsw2d8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGategorieEvenementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.HaFL52N.App\Entity\GategorieEvenement' shared service.
     *
     * @return \App\Entity\GategorieEvenement
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.HaFL52N": it references class "App\\Entity\\GategorieEvenement" but no such service exists.');
    }
}
