<?php

namespace ContainerItsw2d8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mxLQRmV.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.mxLQRmV": it references class "App\\Entity\\Reservation" but no such service exists.');
    }
}
