<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerItsw2d8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerItsw2d8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerItsw2d8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerItsw2d8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerItsw2d8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Itsw2d8',
    'container.build_id' => 'a43f7ee2',
    'container.build_time' => 1670445828,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerItsw2d8');
